/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.YetAnotherFileSharingAppClient;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baronesc
 */
public class KickUserFrame extends javax.swing.JFrame {
    
    private final JFrame parent;
    private final String fileName;
    private final YetAnotherFileSharingAppClient clientInstance;
    private final DefaultTableModel usersTblModel;
    private String[] users;

    /**
     * Creates new form ShareFileFrame
     * @param parent
     * @param fileName
     * @param clientInstance
     */
    public KickUserFrame(JFrame parent, String fileName, YetAnotherFileSharingAppClient clientInstance) {
        
        initComponents();
        
        this.parent = parent;
        this.fileName = fileName;
        this.clientInstance = clientInstance;
        this.usersTblModel = (DefaultTableModel) usersTbl.getModel();
        
        updateTableOfUsers();
        kickUserFilenameLbl.setText("Kick user from \"" + fileName + "\":");
    }
    
    private void updateTableOfUsers() {
        
        users = clientInstance.getListOfUsers(fileName);
        
        usersTblModel.setRowCount(0);
        for (String userName : users) {
            usersTblModel.addRow(new Object[]
            {
                userName
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTbl = new javax.swing.JTable() {
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        kickUserFilenameLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userPrefixTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("YetAnotherFileSharingApp");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("All Users"));

        usersTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Username"
            }
        ));
        usersTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usersTbl);

        kickUserFilenameLbl.setText("Kick user from \"filename\":");

        jLabel2.setText("Filter useres by name:");

        userPrefixTxt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                userPrefixTxtCaretUpdate(evt);
            }
        });
        userPrefixTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPrefixTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(kickUserFilenameLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userPrefixTxt)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kickUserFilenameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userPrefixTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        parent.setEnabled(true);
        parent.toFront();
    }//GEN-LAST:event_formWindowClosed

    private void usersTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTblMouseClicked
        
        if (evt.getClickCount() < 2) {
            return;
        }

        if (usersTbl.getSelectedRow() < 0) {
            return;
        }

        String username = (String) usersTblModel.getValueAt(usersTbl.getSelectedRow(), 0);
        if (clientInstance.ShareFileWith(fileName, username)) {
            JOptionPane.showMessageDialog(new JFrame(), "Invite sent!", "Information!", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "File not found or it isn't yours!", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_usersTblMouseClicked

    private void userPrefixTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPrefixTxtActionPerformed

    }//GEN-LAST:event_userPrefixTxtActionPerformed

    private void userPrefixTxtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_userPrefixTxtCaretUpdate
        
        String prefix = userPrefixTxt.getText();
        
        usersTblModel.setRowCount(0);
        for (String username : users) {
            if (prefix.isEmpty()) {
                usersTblModel.addRow(new Object[]
                {
                    username
                });
            } else if (username.startsWith(prefix)) {
                usersTblModel.addRow(new Object[]
                {
                    username
                });
            }
        }
    }//GEN-LAST:event_userPrefixTxtCaretUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kickUserFilenameLbl;
    private javax.swing.JTextField userPrefixTxt;
    private javax.swing.JTable usersTbl;
    // End of variables declaration//GEN-END:variables
}
