/*
 * YetAnotherFileSharingAppClient - The client side.
 */
package frontend;

import backend.YetAnotherFileSharingAppClient;
import com.sun.glass.events.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert Baronescu
 */
public class NewEmptyFileFrame extends javax.swing.JFrame {

    JFrame parent;    
    YetAnotherFileSharingAppClient clientInstance;

    /**
     * Creates new form NewEmptyFileFrame
     * @param parent
     * @param clientInstance
     */
    public NewEmptyFileFrame(JFrame parent, YetAnotherFileSharingAppClient clientInstance) {

        this.parent = parent;
        this.clientInstance = clientInstance;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fileNameTxt = new javax.swing.JTextField();
        fileExtensionTxt = new javax.swing.JTextField();
        newEmptyFileBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("YetAnotherFileSharingApp");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("New Empty File"));

        jLabel1.setText("Enter a file name:");

        fileNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameTxtActionPerformed(evt);
            }
        });
        fileNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fileNameTxtKeyPressed(evt);
            }
        });

        fileExtensionTxt.setText(".txt");
        fileExtensionTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fileExtensionTxtKeyPressed(evt);
            }
        });

        newEmptyFileBtn.setText("Create new file");
        newEmptyFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmptyFileBtnActionPerformed(evt);
            }
        });
        newEmptyFileBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newEmptyFileBtnKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fileNameTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileExtensionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(newEmptyFileBtn)
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileExtensionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(newEmptyFileBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newEmptyFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmptyFileBtnActionPerformed
        
        if (clientInstance.newEmptyFile(fileNameTxt.getText() +  fileExtensionTxt.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "New file created succesfully.", "Info",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "File already exists on server!", "Error!",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        this.dispose();
    }//GEN-LAST:event_newEmptyFileBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        parent.setEnabled(true);
        parent.toFront();
    }//GEN-LAST:event_formWindowClosed

    private void fileNameTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fileNameTxtKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.newEmptyFileBtnActionPerformed(null);
        }
    }//GEN-LAST:event_fileNameTxtKeyPressed

    private void fileExtensionTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fileExtensionTxtKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.newEmptyFileBtnActionPerformed(null);
        }
    }//GEN-LAST:event_fileExtensionTxtKeyPressed

    private void fileNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameTxtActionPerformed

    private void newEmptyFileBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newEmptyFileBtnKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.newEmptyFileBtnActionPerformed(null);
        }
    }//GEN-LAST:event_newEmptyFileBtnKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fileExtensionTxt;
    private javax.swing.JTextField fileNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newEmptyFileBtn;
    // End of variables declaration//GEN-END:variables
}
